### ISSUE TITLE
More Information Required

### ISSUE THREAD

**Issue by dsm23** [Health-On-Line-Dev/DevTest#1]
The readme is missing 'Prerequisites' and 'How to use' sections. Should the developer be allowed to use the frontend framework of their choice then it is reasonable to assume that the developer may or may not be familiar with .NET, especially a multi-project repo

**Comment by Health-On-Line-Dev** [comment]
You are absolutely right, the aim is to use any framework or frontend you choose and showcase your skills, the test is designed for you to interact with the API given.
I'll make sure that there is an update added to help.

Thanks for the feedback (sorry it has taken a while to respond)
